// LOGIN ACTIONS
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// ACTION TYPES
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_LOCATION = 'GET_LOCATION';
export const SUBMIT_HOODS = 'SUBMIT_HOODS';
